exclude:
- start.bat

timezone: Europe/Berlin
title: WurstClient.net
url: "https://www.wurstclient.net"

# Changes to api.wurstclient.net on GitHub Pages, see jekyll.yml workflow
api_url: "https://api.wurstclient.local"

plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from

author: Alexander01998

feed:
  posts_limit: 20
  collections:
    updates:
      path: "/wurst-updates.xml"

latest_mcversion: "1.21.5"

mcversions:
  "snapshots": "Snapshots"
  "1.19.1": "1.19.84 (1.19.1)"
  "1.14_combat-3": "1.14 Combat Test 3"
  "1.12": "1.12 - 1.12.2"
  "1.12 OF": "1.12 - 1.12.2 + OptiFine"
  "1.11": "1.11 - 1.11.2"
  "1.11 OF": "1.11 - 1.11.2 + OptiFine"
  "1.10": "1.10 - 1.10.2"
  "1.9": "1.9 - 1.9.2"
  "1.8": "1.8 - 1.8.9"
  "1.8 OF": "1.8 - 1.8.9 + OptiFine"
  "1.7": "1.7.2 - 1.7.10"

collections:
  updates:
    output: true
    permalink: /updates/:slug/
  wiki:
    output: true
    permalink: /wiki/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  tutorials_de:
    output: true
    permalink: /de/tutorials/:path/
  redirects:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
    type: pages
  values:
    layout: default
    author: Alexander01998
- scope:
    path: ""
    type: updates
  values:
    layout: update
- scope:
    path: ""
    type: wiki
  values:
    layout: wiki
    secondarytitle: Wurst Wiki
- scope:
    path: ""
    type: tutorials
  values:
    layout: tutorial
- scope:
    path: ""
    type: redirects
  values:
    layout: redirect

mc_update_names:
  "1.7": "The Update That Changed The World"
  "1.8": "The Bountiful Update"
  "1.9": "The Combat Update"
  "1.10": "The Frostburn Update"
  "1.11": "The Exploration Update"
  "1.12": "The World of Color Update"
  "1.14.4": "The Village & Pillage Update"
  "1.15": "The Buzzy Bees Update"
  "1.15.1": "The Buzzy Bees Update"
  "1.15.2": "The Buzzy Bees Update"
  "1.16": "The Nether Update"
  "1.16.1": "The Nether Update"
  "1.16.2": "The Nether Update"
  "1.16.3": "The Nether Update"
  "1.16.4": "The Nether Update"
  "1.16.5": "The Nether Update"
  "1.17": "Caves & Cliffs Part 1"
  "1.17.1": "Caves & Cliffs Part 1"
  "1.18": "Caves & Cliffs Part 2"
  "1.18.1": "Caves & Cliffs Part 2"
  "1.18.2": "Caves & Cliffs Part 2"
  "1.19": "The Wild Update"
  "1.19.1": "The Chat Reports Update"
  "1.19.2": "The Chat Reports Update"
  "1.19.3": "The Wild Update"
  "1.19.4": "The Wild Update"
  "1.20": "The Trails & Tales Update"
  "1.20.1": "The Trails & Tales Update"
  "1.20.2": "The Trails & Tales Update"
  "1.20.3": "The Trails & Tales Update"
  "1.20.4": "The Trails & Tales Update"
  "1.20.5": "The Armored Paws Drop"
  "1.20.6": "The Armored Paws Drop"
  "1.21": "The Tricky Trials Update"
  "1.21.1": "The Tricky Trials Update"
  "1.21.2": "The Bundles of Bravery Drop"
  "1.21.3": "The Bundles of Bravery Drop"
  "1.21.4": "The Garden Awakens Drop"
  "1.21.5": "The Spring To Life Drop"
  "1.21.6": "The Chase The Skies Drop"
